//go:build amd64

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package base

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(Wasi_snapshot_preview1Imports)(nil).Clock_time_get(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Environ_sizes_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_close(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_fdstat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_dir_name(nil, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_prestat_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_read(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_seek(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Fd_write(nil, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Path_open(nil, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Proc_exit(nil, 0)
	(Wasi_snapshot_preview1Imports)(nil).Random_get(nil, 0, 0)
	(Wasi_snapshot_preview1Imports)(nil).Sched_yield(nil)
}
